SGprocesso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('ajax/', include('ajax.urls')),
    #path('utilizador/', include('utilizador.urls')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retornaDadosArquivo/', views.retornaDadosArquivo, name="retorna-dados-arquivo"),
    path('solicitacaoResposta/', views.solicitacaoResposta, name="solicitacao-resposta"),
]

arquivo/urls.py
from django.urls import path
from . import views

app_name = 'arquivo'
urlpatterns = [
    path('registarEntradaProcesso', views.registarEntradaProcesso, name='registar-entrada-processo'),
    path('listar_arquivos', views.listar_arquivos, name='listar-arquivos'),
    path('atribuirNumeroProcesso', views.atribuirNumeroProcesso, name='atribuir-numero-processo'),
    path('numeroProcesso/<int:pk>/', views.numeroProcesso, name='numero-processo'),
    path('show_pdf/<int:pk>/', views.show_pdf, name='show-pdf'),
    path('atualizarDados/<int:pk>/', views.atualizarDados, name='atualizar-dados'),
    path('responderArquivo/<int:pk>/', views.responderArquivo, name='responder-arquivo'),
    path('visualizarArquivoResposta/<int:pk>/', views.visualizarArquivoResposta, name='visualizar-arquivo-resposta'),
]

arquivo/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Topologia(models.Model):
    nome = models.CharField(max_length=100)
    detalhe = models.CharField(max_length=100, blank=True, null=True)
    def __str__ (self):
        return self.nome


class Estado(models.Model):
    nome = models.CharField(max_length=100)
    detalhe = models.CharField(max_length=100, blank=True, null=True)
    def __str__ (self):
        return self.nome


class Departamento(models.Model):
    nome = models.CharField(max_length=100)
    detalhe = models.CharField(max_length=100, blank=True, null=True)
    def __str__ (self):
        return self.nome


class TipoResposta(models.Model):
    nome = models.CharField(max_length=100)
    detalhe = models.CharField(max_length=100, blank=True, null=True)
    def __str__ (self):
        return self.nome


class Arquivo(models.Model):
    tipologia = models.ForeignKey(Topologia, on_delete=models.CASCADE, parent_link=True)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, parent_link=True)
    assunto = models.CharField(max_length=100)
    autor = models.CharField(max_length=70, blank=True, null=True)
    numero_pagina = models.CharField(max_length=5, null=True, blank=True, default="")
    destinatario = models.CharField(max_length=70, blank=True, null=True)
    departamentoDestino = models.ForeignKey(Departamento, on_delete=models.CASCADE, parent_link=True)
    descricao = models.CharField(max_length=670, blank=True, null=True)
    numeroProcesso = models.CharField(max_length=20, blank=True, null=True)
    arquivo = models.FileField(upload_to="uploads/%Y/",blank=True, null=True)
    dataEntrada = models.DateField(default=timezone.now)
    created = models.DateField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    numeroIdentificacao = models.CharField(max_length=20, blank=True, null=True)
    foto = models.ImageField(upload_to='fotos/', blank=True, null=True, default="user.jpg")
    telefone = models.CharField(max_length=20, blank=True, null=True)
    class Meta:
        ordering = ['assunto']
    def __str__ (self):
        return self.id


class Resposta(models.Model):
    arquivo = models.ForeignKey(Arquivo, on_delete=models.CASCADE, parent_link=True)
    tipoResposta = models.ForeignKey(TipoResposta, on_delete=models.DO_NOTHING, blank=True, null=True, parent_link=True)
    msg = models.CharField(max_length=10990, blank=True, null=True)
    titulo = models.CharField(max_length=200, blank=True, null=True)
    solicitacao = models.BooleanField(blank=True, null=True)
    dataEntrada = models.DateField(default=timezone.now)
    created = models.DateField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    def __str__ (self):
        return self.id

arquivo/forms.py
from django import forms
from django.forms import ModelForm
from arquivo.models import Arquivo, Topologia, Estado, Resposta, Departamento



CATEGORIA = []
ESTADO = []
DEPARTAMENTO = []


CATEGORIA.append(['', '---------'])
for x in Topologia.objects.all():
    CATEGORIA.append([int(x.id), str(x.nome)])


ESTADO.append(['', '---------'])
for x in Estado.objects.all():
    ESTADO.append([int(x.id), str(x.nome)])


DEPARTAMENTO.append(['', '---------'])
for x in Departamento.objects.all():
    DEPARTAMENTO.append([int(x.id), str(x.nome)])
 

class Arquivo_Form(ModelForm):
    assunto = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control '}))
    numero_pagina = forms.CharField(max_length=40,required=False, widget=forms.TextInput(attrs={'class': 'form-control maiuscula'}))
    numeroIdentificacao = forms.CharField(max_length=40, required=False,widget=forms.TextInput(attrs={'class': 'form-control maiuscula'}))
    autor = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    telefone = forms.CharField(max_length=30,required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    numeroProcesso = forms.CharField(max_length=180, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    destinatario = forms.CharField(max_length=60,required=False,  widget=forms.TextInput( attrs={'class': 'form-control'}))
    arquivo = forms.FileField(required=False, widget=forms.FileInput(attrs={'type': 'file', 'class': 'form-control'}))
    descricao = forms.CharField(max_length=510,required=False, widget=forms.Textarea(attrs={ 'class': 'form-control '}))
    foto = forms.CharField(required=False, widget=forms.TextInput(attrs={'type':'hidden', 'class': 'form-control', 'id': 'fotoSalva'}))
    class Meta:
        model = Arquivo
        fields = ['tipologia','estado', 'departamentoDestino', 'dataEntrada','descricao','assunto', 'numero_pagina',
         'autor','numeroProcesso', 'destinatario','numeroIdentificacao', 'arquivo', 'foto']

        widgets = {
            'tipologia': forms.Select(attrs={'class': 'form-control'}),
            'estado': forms.Select( attrs={'class': 'form-control'}),
            'departamentoDestino': forms.Select( attrs={'class': 'form-control'}),
            'dataEntrada': forms.DateInput(attrs={'type': 'date','class': 'form-control'}),
        }



class Resposta_Form(ModelForm):
    titulo = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control '}))
    msg = forms.CharField(max_length=10990, widget=forms.Textarea(attrs={ 'class': 'form-control html-editor', 'rows':'12'}))
    arquivo = forms.CharField(max_length=4, required=False, widget=forms.TextInput(attrs={'class': 'form-control '}))
    departamentoDestino = forms.CharField(max_length=160, widget=forms.Select(choices=DEPARTAMENTO, attrs={'class': 'form-control'}))
    class Meta:
        model = Resposta
        fields = ['tipoResposta','dataEntrada','msg', 'titulo']

        widgets = {
            'tipoResposta': forms.Select(attrs={'class': 'form-control'}),
            'dataEntrada': forms.DateInput(attrs={'type': 'date','class': 'form-control'}),
        }

    """def clean_msg(self):
        msg = self.cleaned_data.get('msg')
        max_file_size = 10840
        if int(nota_final) > 9 and int(nota_final) <= 20:
            return nota_final
        else:
            raise forms.ValidationError("A media final não é valida")"""

class Consultar_form(forms.Form):
    numeroIdentificacao = forms.CharField(max_length=10,required=False, widget=forms.TextInput(attrs={'class': 'form-control '}))
    categoria = forms.CharField(max_length=160,required=False, widget=forms.Select(choices=CATEGORIA, attrs={'class': 'form-control'}))
    estado = forms.CharField(max_length=160,required=False, widget=forms.Select(choices=ESTADO, attrs={'class': 'form-control'}))
    dataEntrada = forms.CharField(max_length=20,required=False, widget=forms.TextInput(attrs={'type': 'date','class': 'form-control'}))
    
  
class NumeroProcesso_form(forms.Form):
    numeroIdentificacao = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control '}))
   

arquivo/views.py
from multiprocessing import context
from django.http import JsonResponse, HttpRequest,FileResponse,HttpResponse,HttpResponseRedirect
from django.db.models import Q
import os, json
from django.urls import reverse
from django.shortcuts import render
from arquivo.models import Arquivo, Resposta
from arquivo.forms import  Arquivo_Form, Consultar_form, NumeroProcesso_form,Resposta_Form



def show_pdf(request, pk):
    filepath = ""
    context = ""
    if pk is not None:
        lista = Arquivo.objects.get(id=int(pk))
        filepath = os.path.join('media', str(lista.arquivo))
        fs = open(filepath, 'rb')
    return HttpResponse(open(filepath, 'rb'), content_type='application/pdf')



def atribuirNumeroProcesso(request):
    form = NumeroProcesso_form(request.POST or None)
    if request.method == "POST":
        bi = request.POST['numeroIdentificacao']
        lista = Arquivo.objects.filter(numeroIdentificacao=bi)
        context = {'lista': lista}
        return render (request, 'arquivos/listarNumeroProcesso.html', context)
    context = {'form': form}
    return render (request, 'arquivos/atribuirNumeroProcesso.html', context)


def visualizarArquivoResposta(request, pk):

    context = {}
    return render (request, 'arquivos/reciboEntrada.html', context)



def numeroProcesso(request, pk):
    form = NumeroProcesso_form(request.POST or None)
    if request.method == "POST":
        lista = Arquivo.objects.get(id=pk)
        # lista.numeroProcesso=
        context = {}
        return render (request, 'arquivos/listarNumeroProcesso.html', context)

    context = {'form': form}
    return render (request, 'arquivos/atribuirNumeroProcesso.html', context)



def responderArquivo(request, pk):    
    form = Resposta_Form(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            msg = request.POST['msg']
            titulo = request.POST['titulo']
            tipoResposta = request.POST['tipoResposta']
            data = request.POST['dataEntrada']
            departamentoDestino = request.POST['departamentoDestino']

            lista = Arquivo.objects.select_related('estado').get(id=pk)
            lista.estado_id = 4
            lista.departamentoDestino = departamentoDestino
            lista.save()
            try:
               resp = Resposta.objects.get(arquivo_id=pk)
               resp.msg = msg
               resp.titulo = titulo
               resp.tipoResposta_id = tipoResposta
               resp.dataEntrada = data
               resp.solicitacao = False
               resp.save()
            
            except Resposta.DoesNot:
                resp = form.save(commit=False)
                resp.solicitacao = False
                resp.save()

            context = {'dados':lista,'form':form}
            return render (request, 'arquivos/sucessoResposta.html')

    context = {'form': form,'pk':pk}
    return render (request, 'arquivos/responderArquivo.html', context)


def atualizarDados(request, pk):
    sucesso = False
    dados = Arquivo.objects.get(id=int(pk))
    form = Arquivo_Form(request.POST or None, instance=dados)
    context = {'form': form, 'pk':pk}
    if request.method == "POST":
            form = Arquivo_Form(request.POST or None, request.FILES, instance=dados)
            if form.is_valid():
                form.save()
                #context = {'dados':form.cleaned_data, 'sucesso': sucesso}
                #return render (request, 'arquivos/reciboEntrada.html', context)
                #form = Arquivo_Form()
                #context = {'form': form, 'sucesso':True}
                return HttpResponseRedirect(reverse('home:dashboard'))
    return render (request, 'arquivos/registarProcesso.html', context)


def listar_arquivos(request):
    form = Consultar_form(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            bi = request.POST['numeroIdentificacao']
            categoria = request.POST['categoria']
            estado = request.POST['estado']
            dataEntrada = request.POST['dataEntrada']

            print(dataEntrada)
            
            if bi and categoria and estado and dataEntrada:
                
                lista = Arquivo.objects.select_related('estado').filter(Q(numeroIdentificacao=bi)|Q(tipologia=categoria)|Q(estado=estado)|Q(dataEntrada=dataEntrada))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
            
            elif bi and categoria and dataEntrada:
                lista = Arquivo.objects.select_related('estado').filter(Q(numeroIdentificacao=bi)|Q(tipologia=categoria)|Q(dataEntrada=dataEntrada))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
            
            elif bi and estado and dataEntrada:
                lista = Arquivo.objects.select_related('estado').filter(Q(numeroIdentificacao=bi)|Q(estado=estado)|Q(dataEntrada=dataEntrada))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)

            elif categoria and estado and dataEntrada:
                
                lista = Arquivo.objects.select_related('estado').filter(Q(tipologia=categoria)|Q(estado=estado))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
           
            elif categoria and dataEntrada:
                
                lista = Arquivo.objects.select_related('estado').filter(Q(tipologia=categoria)|Q(dataEntrada=dataEntrada))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
            
            elif estado and dataEntrada:
                
                lista = Arquivo.objects.select_related('estado').filter(Q(dataEntrada=dataEntrada)|Q(estado=estado))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)

            elif categoria and estado:
                lista = Arquivo.objects.select_related('estado').filter(Q(tipologia=categoria)|Q(estado=estado))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
            
            elif bi and dataEntrada:
                lista = Arquivo.objects.select_related('estado').filter(Q(numeroIdentificacao=bi)|Q(dataEntrada=dataEntrada))
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)

            elif bi:
                lista = Arquivo.objects.select_related('estado').filter(numeroIdentificacao=bi)
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
            
            elif estado:
                lista = Arquivo.objects.select_related('estado').filter(estado=estado)
                context = {'lista':lista}
                return render (request, 'arquivos/listarArquivo.html', context)
    
    context = {'form':form}
    return render (request, 'arquivos/consultar.html', context)




#@login_required -> True if you want to love..
def registarEntradaProcesso(request):
    form = Arquivo_Form(request.POST or None)
    if request.method == "POST":
        form = Arquivo_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            #bi = request.POST['numeroIdentificacao']
            sucesso = True
            context = {'dados':form.cleaned_data, 'sucesso': sucesso}
            return render (request, 'arquivos/reciboEntrada.html', context)
        
    context = {'form': form}
    return render (request, 'arquivos/registarProcesso.html', context)

templates/arquivos/atribuirNumeroProcesso.html
{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
   
    <div class="card" style="min-height: 484px">
          <div class="card-header">
           
          <h3>Consultar o Processo</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'arquivo:atribuir-numero-processo' %}" method="POST" >
              {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-10">
                  <div class="form-group">
                    <label for="" class="">Número de Identificação:<span class="text-danger"></span></label>
                    {{ form.numeroIdentificacao }}{{ form.numeroIdentificacao.errors }}
                    
                  </div>
                </div>
              </div>
             

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">Consultar</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/arquivos/consultar.html
{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
   
    <div class="card" style="min-height: 484px">
          <div class="card-header">
           
          <h3>Consultar Listagem</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'arquivo:listar-arquivos' %}" method="POST" >
              {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Número de Identificação:<span class="text-danger"></span></label>
                    {{ form.numeroIdentificacao }}{{ form.numeroIdentificacao.errors }}
                    
                  </div>
                </div>

                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Categoria:<span class="text-danger"></span></label>
                      {{ form.categoria }}{{ form.categoria.errors }}
                    
                    
                  </div>
                </div>
              </div>
              
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Estado do Documento<span class="text-danger"></span></label>
                    {{ form.estado }}{{ form.estado.errors }}
                    
                  </div>
                </div>

                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Data de Entrada<span class="text-danger"></span></label>
                    {{ form.dataEntrada }}{{ form.dataEntrada.errors }}
                    
                  </div>
                </div>
                
              </div>
              
              <div class="row">
              </div>

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">Consultar</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/arquivos/listarArquivo.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-03-26 20:36:36
@modify date 2022-06-10 04:12:08
@desc [description]
-->

{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="card">
 
  <div class="card-body">
     <div class="card-header row"><h3><b>LISTA DE PROCESSO</b></h3></div>
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Assunto</th>
          <th>Destinatario</th>
          <th>Departamento</th>
          <th>Estado</th>
          <th>Data de Entrada</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">{{ dados.autor|upper }}</td>
          <td class="">{{ dados.assunto|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.destinatario|upper }}</td>
          <td class="">{{ dados.departamentoDestino|upper }}</td>
          <td class=""><b>{{ dados.estado|upper }}</b></td>
          <td class="">{{ dados.dataEntrada }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i>
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'arquivo:atualizar-dados' dados.id  %}">Atualizar</a>
                  <a class="dropdown-item" href="#" onclick="detalhesArquivo({{ dados.id }})"> Descrição</a>
                  <a class="dropdown-item" href="{% url 'arquivo:show-pdf' dados.id  %}" target="_blank">Visualizar Arquivo de</br> Entrada</a>
                  <a class="dropdown-item" href="{% url 'arquivo:visualizar-arquivo-resposta' dados.id  %}" >Visualizar Arquivo de</br> Resposta</a>
                  <a class="dropdown-item" href="#" onclick="solicitacaoResposta({{ dados.id }})" data-toggle="modal" data-target="#respostaModal">Solicitar Resposta</a>
                  <a class="dropdown-item" href="{% url 'arquivo:responder-arquivo' dados.id  %}" ">Responder</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="modal fade edit-layout-modal" id="editLayoutItem" tabindex="-1" role="dialog" aria-labelledby="editLayoutItemLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editLayoutItemLabel">Descrição do Arquivo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p class="lead"></p>
        <div id="descricao"></div>
        <!--<div class="row">
                  <div class="col-md-6"><img src="../img/portfolio-1.jpg" class="img-fluid" alt=""></div>
                  <div class="col-md-6"><img src="../img/portfolio-8.jpg" class="img-fluid" alt=""></div>
              </div>
        <div class="jumbotron pt-30 pb-30 mt-30">
          <h2 class="mt-0"></h2>
          <p class="lead"></p>
        </div>
        -->
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="respostaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterLabel">Solicitação</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body" id="mensagem">...</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

  <script>
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        var cookies = document.cookie.split(";");
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    function detalhesArquivo(id) {
      $.ajax({
        url: "/ajax/retornaDadosArquivo/",
        type: "POST",
        data: JSON.stringify({ id: id }),
        dataType: "json",
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
          Accept: "application/json",
          "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        },
        success: function (data) {
          document.getElementById("descricao").innerHTML = "<p><h4>" + data.descricao + "</h4></p>";
          $("#editLayoutItem").modal("show");
        },
        error: function () {
          console.log("erro ao aprovar inscricao" + data);
        },
      });
    }

    // função que vai solicitar uma resposta do arquivo
    function solicitacaoResposta(id) {
      $.ajax({
        url: "/ajax/solicitacaoResposta/",
        type: "POST",
        data: JSON.stringify({ id: id }),
        dataType: "json",
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
          Accept: "application/json",
          "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        },
        success: function (data) {
          document.getElementById("mensagem").innerHTML = "<p><h4>" + data.msg + "</h4></p>";
          $("#respostaModal").modal("show");
        },
        error: function () {
          console.log("erro ao aprovar inscricao" + data);
        },
      });
    }
  </script>

  {% endblock %}
</div>

templates/arquivos/listarNumeroProcesso.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-03-26 20:36:36
@modify date 2022-05-13 01:19:36
@desc [description]
-->

{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Processo Pessoal</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Assunto</th>
          <th>Destinatario</th>
          <th>Departamento</th>
          <th>Estado</th>
          <th>Nº do Processo</th>
          <th>Data de Entrada</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">{{ dados.autor|upper }}</td>
          <td class="">{{ dados.assunto|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.destinatario|upper }}</td>
          <td class="">{{ dados.departamentoDestino|upper }}</td>
          <td class="">{{ dados.estado|upper }}</td>
          <td class="">{{ dados.numeroProcesso|upper }}</td>
          <td class="">{{ dados.dataEntrada }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'arquivo:numero-processo' dados.id %}">Atribuir Número de Processo</a>
                  <a class="dropdown-item" href="">Atualizar</a>

                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/arquivos/showPdf.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-03-26 20:36:36
@modify date 2022-05-19 16:44:31
@desc [description]
-->

{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Arquivo</h3></div>
  <div class="card-body">
    <embed type="application/pdf" src="./../media/{{ name }}" width="500px" height="678px" /></embed>
  </div>
</div>

{% endblock %}

templates/arquivos/sucessoResposta.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-06-06 18:02:50
@modify date 2022-06-06 18:26:47
@desc [description]
-->

{% extends 'base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-body">
    <div class="card-header row">
      <h3><b></b></h3>

      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="widget bg-success">
          <div class="widget-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="state">
                <h2>Resposta Enviada com sucesso..</h2>
                <h6>Visualizar o arquivo</h6>
              </div>
              <div class="icon">
                <i class="ik ik-shopping-cart"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}