SGprocesso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('ajax/', include('ajax.urls')),
    #path('utilizador/', include('utilizador.urls')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retornaDadosArquivo/', views.retornaDadosArquivo, name="retorna-dados-arquivo"),
    path('solicitacaoResposta/', views.solicitacaoResposta, name="solicitacao-resposta"),
]

arquivo/urls.py
from django.urls import path
from . import views

app_name = 'arquivo'
urlpatterns = [
    path('registarEntradaProcesso', views.registarEntradaProcesso, name='registar-entrada-processo'),
    path('listar_arquivos', views.listar_arquivos, name='listar-arquivos'),
    path('atribuirNumeroProcesso', views.atribuirNumeroProcesso, name='atribuir-numero-processo'),
    path('numeroProcesso/<int:pk>/', views.numeroProcesso, name='numero-processo'),
    path('show_pdf/<int:pk>/', views.show_pdf, name='show-pdf'),
    path('atualizarDados/<int:pk>/', views.atualizarDados, name='atualizar-dados'),
    path('responderArquivo/<int:pk>/', views.responderArquivo, name='responder-arquivo'),
    path('visualizarArquivoResposta/<int:pk>/', views.visualizarArquivoResposta, name='visualizar-arquivo-resposta'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('dashboard', views.home, name='dashboard'),
]

utilizador/urls.py
from django.urls import path
from . import views

app_name = 'utilizador'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginUser, name='loginUser'),
    path('criarContaUtilizador', views.criarContaUtilizador, name="criar-conta-utilizador"),
]

templates/base.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-03-23 05:41:23
@modify date 2022-06-24 13:41:51
@desc [description]
-->

<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <!--  <meta http-equiv="refresh" content="60" />-->
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>XSof - Sistema de Gestão de Arquivos</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'img/so.jpeg' %}" type="image/x-icon" />

    <link rel="stylesheet" href="{% static '/plugins/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/fontawesome-free/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/icon-kit/dist/css/iconkit.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/ionicons/dist/css/ionicons.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/jquery-toast-plugin/dist/jquery.toast.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" />
    <!--<link rel="stylesheet" href="{% static '/plugins/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css' %}" />-->
    <link rel="stylesheet" href="{% static '/plugins/weather-icons/css/weather-icons.min.css' %}" />
    <!--<link rel="stylesheet" href="{% static '/plugins/c3/c3.min.css' %}" />-->
    <link rel="stylesheet" href="{% static '/dist/css/sweetalert2.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/summernote/dist/summernote-bs4.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/owl.carousel/dist/assets/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/owl.carousel/dist/assets/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/theme.min.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/wizard.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/custum.css' %}" />
    <script src="{% static '/src/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <script src="{% static '/src/js/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/plugins/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static '/highcharts/highmaps.js' %}"></script>
    <script src="{% static '/highcharts/highcharts.js' %}"></script>
    <script src="{% static '/highcharts/highcharts-3d.js' %}"></script>
    <script src="{% static '/highcharts/sunburst.js' %}"></script>
    <script src="{% static '/highcharts/cylinder.js' %}"></script>

    <script src="{% static '/highcharts/exporting.js' %}"></script>
  </head>

  <body>
    <!--[if lt IE 8]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->

    <div class="wrapper">
      <header class="header-top" header-theme="light">
        <div class="container-fluid">
          <div class="d-flex justify-content-between">
            <div class="top-menu d-flex align-items-center">
              <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
              <div class="header-search">
                <div class="input-group">
                  <span class="input-group-addon search-close"><i class="ik ik-x"></i></span>
                  <input type="text" class="form-control" />
                  <span class="input-group-addon search-btn"><i class="ik ik-search"></i></span>
                </div>
              </div>
              <button type="button" id="navbar-fullscreen" class="nav-link"><i class="ik ik-maximize"></i></button>
            </div>
            <div class="top-menu d-flex align-items-center">
              <div class="dropdown">
                <a class="dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  ><img class="avatar" src="{% static 'img/user.png' %}" alt=""
                /></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                  <a class="dropdown-item" href="#"><i class="ik ik-user dropdown-icon"></i> Profile</a>
                  <a class="dropdown-item" href="#"><i class="ik ik-power dropdown-icon"></i> Logout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div class="page-wrap">
        <div class="app-sidebar colored">
          <div class="sidebar-header">
            <a class="header-brand" href="{% url 'home:dashboard' %}">
              <div class="logo-img">
                <!-- <img src="src/img/brand-white.svg" class="header-brand-img" alt="lavalite" />-->
              </div>
              <span class="text">XSOF<br /></span>
            </a>
            <button type="button" class="nav-toggle"><i data-toggle="expanded" class="ik ik-toggle-right toggle-icon"></i></button>
            <button id="sidebarClose" class="nav-close"><i class="ik ik-x"></i></button>
          </div>

          <div class="sidebar-content">
            <div class="nav-container">
              <nav id="main-menu-navigation" class="navigation-main">
                <div class="nav-item active">
                  <a href="#"><i class="ik ik-bar-chart-2"></i><span>MENU</span></a>

                <div class="nav-item has-sub">
                  <div class="">
                    <a href="{% url 'arquivo:registar-entrada-processo' %}" class="menu-item">Registar Nova Entrada</a>
                    <a href="{% url 'arquivo:listar-arquivos' %}" class="menu-item">Listar Processos</a>
                    <a href="{% url 'arquivo:atribuir-numero-processo' %}" class="menu-item">Atribuir Número de Processo</a>
                    <a href="{% url 'arquivo:listar-arquivos' %}" class="menu-item">Consultar Processo</a>
                    <a href="{% url 'utilizador:criar-conta-utilizador' %}" class="menu-item">Criar Conta de Utilizador</a>
                    <!--<a href="" class="menu-item">Listar Conta de Utilizador</a>-->
                  </div>
                </div>
                <!--<div class="nav-lavel">DIRECTOR</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-book-open"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="" class="menu-item">Encaminhar Arquivo</a>
                  </div>
                </div>
                <div class="nav-lavel">REPARTIÇÃO DE <br />INVESTIGAÇÃO</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-book-open"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="{% url 'arquivo:listar-arquivos' %}" class="menu-item">Listar solicitação</a>
                  </div>
                </div>
                <div class="nav-lavel">REPARTIÇÃO DE INSTRUÇÃO</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-book-open"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="{% url 'arquivo:listar-arquivos' %}" class="menu-item">Listar solicitação</a>
                  </div>
                </div>

                <div class="nav-lavel">UTILIZADOR</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-users"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="{% url 'utilizador:criar-conta-utilizador' %}" class="menu-item">Criar Conta de Utilizador</a>
                  </div>
                </div>-->
              </nav>
            </div>
          </div>
        </div>
        <div class="main-content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <!--<div id="visitfromworld" style="width: 100%; height: 350px"></div>-->
                {% block corpo %} centro {% endblock %}
              </div>
            </div>
          </div>
        </div>

        <footer class="footer">
          <div class="w-100 clearfix">
            <span class="text-center text-sm-left d-md-inline-block">Copyright © 2022 XSof - Sistema de Gestão de Arquivos </span>
            <span class="float-none float-sm-right mt-1 mt-sm-0 text-center"><i class="fa fa-heart text-danger"></i> <a href="#" class="text-dark" target="_blank">v1.0.</a></span>
          </div>
        </footer>
      </div>
    </div>

    <script src="{% static '/plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/dist/js/webcam.js' %}"></script>
    <script src="{% static '/dist/js/html2pdf.bundle.min.js' %}"></script>
    <script src="{% static '/dist/js/sweetalert2.js' %}"></script>
    <script src="{% static '/plugins/jquery-toast-plugin/dist/jquery.toast.min.js' %}"></script>
    <script src="{% static '/js/alerts.js' %}"></script>
    <!--<script src="{% static '/dist/js/pdf.min.js' %}"></script>-->

    <script src="{% static '/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static '/plugins/screenfull/dist/screenfull.js' %}"></script>
    <script src="{% static '/plugins/summernote/dist/summernote-bs4.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static '/plugins/moment/moment.js' %}"></script>
    <!--<script src="{% static '/plugins/d3/dist/d3.min.js' %}"></script>
    <script src="{% static '/plugins/c3/c3.min.js' %}"></script>-->
    <script src="{% static '/dist/js/tables.js' %}"></script>
    <script src="{% static '/dist/js/layouts.js' %}"></script>
    <script src="{% static '/dist/js/wizerd.js' %}"></script>
    <script src="{% static '/dist/js/help/foto.js' %}"></script>
    <script src="{% static '/dist/js/help/request.js' %}"></script>
    <script src="{% static '/dist/js/theme.min.js' %}"></script>
    <script language="JavaScript">
      // Configure a few settings and attach camera
      function configure() {
        Webcam.set({
          width: 240,
          height: 240,
          image_format: "jpeg",
          jpeg_quality: 90,
        });
        Webcam.attach("#my_camera");
      }
    </script>
  </body>
</html>